// frontend/src/App.tsx
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Route, Routes } from "react-router-dom";
import Layout from "@/components/layout/layout";
import { Toaster } from "sonner";
import Dashboard from "@/pages/dashboard";
import Login from "@/features/auth/pages/login";
import { useAuthStore } from "@/features/auth/stores/authStore";
import { useEffect } from "react";
import SignUp from "./features/auth/pages/sign-up";
import ForgotPassword from "./features/auth/pages/forgot-password";
import { RequireAuth } from "./components/layout/require-auth";
import RolesList from "./pages/roles/roles-list";

function App() {
  const initialize = useAuthStore((state) => state.initialize);
  const isLoading = useAuthStore((state) => state.isInitializing);

  useEffect(() => {
    initialize();
  }, [initialize]);

  if (isLoading) {
    return <></>;
  }

  return (
    <ThemeProvider defaultTheme="system" storageKey="vite-ui-theme">
      <Toaster richColors />

      <Routes>
        <Route path="/login" element={<Login />} />
        <Route path="/sign-up" element={<SignUp />} />
        <Route path="/forgot-password" element={<ForgotPassword />} />

        <Route element={<RequireAuth />}>
          <Route element={<Layout />}>
            <Route path="/" element={<Dashboard />} />
            <Route path="/roles" element={<RolesList />} />
          </Route>
        </Route>
      </Routes>
    </ThemeProvider>
  );
}

export default App;

// solid-frontend/src/App.tsx
import "@/App.css";
import Layout from "@/components/layout/Layout";
import { RequireAuth } from "@/components/layout/RequireAuth";
import Login from "@/features/auth/pages/Login";
import { Route, Router } from "@solidjs/router";

import { ColorModeProvider } from "@kobalte/core";
import { lazy, onMount, Show } from "solid-js";
import { authService } from "@/features/auth/services/authService";
import { authStore } from "@/features/auth/stores/authStore";
import { Toaster } from "@/components/ui/sonner";

const Home = lazy(() => import("@/pages/home"));
const RolesList = lazy(() => import("@/features/roles/pages/RolesList"));

function App() {
  onMount(() => {
    authService.initialize();
  });

  return (
    <Show when={!authStore.isInitializing}>
      <ColorModeProvider initialColorMode="system">
        <Toaster />
        <Router>
          {/* Unprotected Routes */}
          <Route path="/login" component={Login} />

          {/* Protected Routes With Auth/Layout */}
          <Route component={RequireAuth}>
            <Route component={Layout}>
              <Route path="/" component={Home} />

              {/* Roles */}
              <Route path="/roles">
                <Route path="/" component={RolesList} />
              </Route>
            </Route>
          </Route>
        </Router>
      </ColorModeProvider>
    </Show>
  );
}

export default App;
