// frontend/src/app.tsx
import { ThemeProvider } from "@/components/providers/theme_provider";
import { Route, Routes } from "react-router-dom";
import Layout from "@/components/layout/layout";
import { Toaster } from "sonner";
import Login from "@/features/auth/pages/login";
import { useAuthStore } from "@/features/auth/stores/auth_store";
import { lazy, Suspense, useEffect } from "react";
import SignUp from "./features/auth/pages/sign_up";
import ForgotPassword from "./features/auth/pages/forgot_password";
import { RequireAuth } from "./components/layout/require_auth";

function App() {
  const initialize = useAuthStore((state) => state.initialize);
  const isLoading = useAuthStore((state) => state.isInitializing);

  const Dashboard = lazy(() => import("@/pages/dashboard"));
  const RolesList = lazy(() => import("@/features/roles/pages/roles_list"));
  const UsersList = lazy(() => import("@/features/users/pages/users_list"));
  const RecipesList = lazy(() => import("@/features/recipes/pages/recipes_list"));

  useEffect(() => {
    initialize();
  }, [initialize]);

  if (isLoading) {
    return <></>;
  }

  return (
    <ThemeProvider defaultTheme="system" storageKey="vite-ui-theme">
      <Toaster richColors />
      <Suspense>
        <Routes>
          {/* Unprotected Routes */}
          <Route path="/login" element={<Login />} />
          <Route path="/sign-up" element={<SignUp />} />
          <Route path="/forgot-password" element={<ForgotPassword />} />

          {/* Authenticated Routes */}
          <Route element={<RequireAuth />}>
            <Route element={<Layout />}>
              <Route path="/" element={<Dashboard />} />

              {/* Roles */}
              <Route path="/roles">
                <Route path="" element={<RolesList />} />
              </Route>

              {/* Users */}
              <Route path="/users">
                <Route path="" element={<UsersList />} />
              </Route>

              {/* Recipes */}
              <Route path="/recipes">
                <Route path="" element={<RecipesList />} />
              </Route>
            </Route>
          </Route>
        </Routes>
      </Suspense>
    </ThemeProvider>
  );
}

export default App;

// solid-frontend/src/App.tsx
import "@/App.css";
import Layout from "@/components/layout/Layout";
import { RequireAuth } from "@/components/layout/RequireAuth";
import Login from "@/features/auth/pages/Login";
import { Route, Router } from "@solidjs/router";

import { ColorModeProvider } from "@kobalte/core";
import { lazy, onMount, Show } from "solid-js";
import { authService } from "@/features/auth/services/authService";
import { authStore } from "@/features/auth/stores/authStore";
import { Toaster } from "@/components/ui/sonner";

const Home = lazy(() => import("@/pages/home"));
const RolesList = lazy(() => import("@/features/roles/pages/RolesList"));

function App() {
  onMount(() => {
    authService.initialize();
  });

  return (
    <Show when={!authStore.isInitializing}>
      <ColorModeProvider initialColorMode="system">
        <Toaster />
        <Router>
          {/* Unprotected Routes */}
          <Route path="/login" component={Login} />

          {/* Protected Routes With Auth/Layout */}
          <Route component={RequireAuth}>
            <Route component={Layout}>
              <Route path="/" component={Home} />

              {/* Roles */}
              <Route path="/roles">
                <Route path="/" component={RolesList} />
              </Route>
            </Route>
          </Route>
        </Router>
      </ColorModeProvider>
    </Show>
  );
}

export default App;
