// solid-frontend/src/components/layout/require-auth.tsx
import { authStore } from "@/features/auth/stores/authStore";
import { Navigate } from "@solidjs/router";
import { type JSX } from "solid-js";

export function RequireAuth(props: { children?: JSX.Element }) {
  if (!authStore.user) {
    return <Navigate href="/login" />;
  }

  return props.children;
}

// frontend/src/components/layout/require_auth.tsx
import { Navigate, Outlet } from "react-router-dom";
import { useAuthStore } from "@/features/auth/stores/auth_store";

export function RequireAuth() {
  const isLoggedIn = useAuthStore((s) => s.isLoggedIn);

  if (!isLoggedIn) {
    return <Navigate to="/login" replace />;
  }

  return <Outlet />;
}
