// solid-frontend/src/components/layout/AppSidebar.tsx
import { Book, BookLock, ChevronUp, UserRound, House } from "lucide-solid";

import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from "@/components/ui/sidebar";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { AuthenticatedUser } from "@/features/auth/types";
import { ROLES } from "@/features/roles/types";
import { toast } from "somoto";
import { ModeToggle } from "@/components/ui/mode-toggle";
import { A } from "@solidjs/router";
import { For, Show } from "solid-js";
import { authService } from "@/features/auth/services/authService";
import { authStore } from "@/features/auth/stores/authStore";

type Icon = typeof House;

interface IMenuItem {
  title: string;
  url: string;
  icon: Icon;
  canAccess: (user: AuthenticatedUser | null) => boolean;
}

// Menu items.
const items: IMenuItem[] = [
  {
    title: "Home",
    url: "/",
    icon: House,
    canAccess: (_: AuthenticatedUser | null) => true,
  },
  {
    title: "Roles",
    url: "/roles",
    icon: BookLock,
    canAccess: (user: AuthenticatedUser | null) => user !== null && user.isAdmin,
  },
  {
    title: "Recipes",
    url: "/recipes",
    icon: Book,
    canAccess: (user: AuthenticatedUser | null) =>
      user !== null && (user.hasRole(ROLES.RecipeUser) || user.isAdmin),
  },
];

type AppSidebarProps = {
  variant?: "inset" | "floating" | "sidebar";
};

export default function AppSidebar({ variant }: AppSidebarProps) {
  const handleLogout = async () => {
    try {
      await authService.logout();
      toast.success("Logout Successful");
    } catch (error) {
      if (error instanceof Error) {
        toast.error(`Failed to logout: ${error.message}`);
      } else {
        toast.error("Failed to logout");
      }
    }
  };

  return (
    <Sidebar variant={variant}>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel class="text-md mb-2">Mainframe</SidebarGroupLabel>
          <ModeToggle />
          <SidebarGroupContent>
            <SidebarMenu>
              <For each={items}>
                {(item) => (
                  <Show when={item.canAccess(authStore.user)}>
                    <SidebarMenuItem>
                      <SidebarMenuButton as={A} href={item.url}>
                        <item.icon />
                        <span>{item.title}</span>
                      </SidebarMenuButton>
                    </SidebarMenuItem>
                  </Show>
                )}
              </For>
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
      <SidebarFooter>
        <SidebarMenu>
          <SidebarMenuItem>
            <DropdownMenu>
              <DropdownMenuTrigger class="w-full">
                <SidebarMenuButton class="justify-center relative">
                  <UserRound class="absolute left-2" />
                  <span>{authStore.user ? authStore.user.fullName : "Guest"}</span>
                  <ChevronUp class="absolute right-2 h-4 w-4" />
                </SidebarMenuButton>
              </DropdownMenuTrigger>
              <DropdownMenuContent class="w-[var(--kb-popper-anchor-width)]">
                <DropdownMenuItem onClick={handleLogout}>
                  <span>Logout</span>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarFooter>
    </Sidebar>
  );
}

// frontend/src/shared/layout/app_sidebar.tsx
import { Book, BookLock, ChevronUp, Cookie, Home, User, User2 } from "lucide-react";

import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from "@/shared/ui/sidebar";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/shared/ui/dropdown_menu";
import { AuthenticatedUser } from "@/features/auth/types";
import { ROLES } from "@/features/roles/types";
import { toast } from "sonner";
import { ModeToggle } from "./mode_toggle";
import { Link, useLocation } from "@tanstack/react-router";
import { currentUserQueryOptions, useLogout } from "@/features/auth/queries";
import { useQuery } from "@tanstack/react-query";

type Icon = typeof Home;

interface IMenuItem {
  title: string;
  url: string;
  icon: Icon;
  canAccess: (user?: AuthenticatedUser | null) => boolean;
}

// Menu items.
const items: IMenuItem[] = [
  {
    title: "Home",
    url: "/",
    icon: Home,
    canAccess: () => true,
  },
  {
    title: "Recipes",
    url: "/recipes",
    icon: Book,
    canAccess: (user?: AuthenticatedUser | null) =>
      user !== undefined && user !== null && (user.hasRole(ROLES.RecipeUser) || user.isAdmin),
  },
  {
    title: "Roles",
    url: "/roles",
    icon: BookLock,
    canAccess: (user?: AuthenticatedUser | null) =>
      user !== undefined && user !== null && user.isAdmin,
  },
  {
    title: "Sessions",
    url: "/sessions",
    icon: Cookie,
    canAccess: (user?: AuthenticatedUser | null) =>
      user !== undefined && user !== null && user.isAdmin,
  },
  {
    title: "Users",
    url: "/users",
    icon: User,
    canAccess: (user?: AuthenticatedUser | null) =>
      user !== undefined && user !== null && user.isAdmin,
  },
];

type AppSidebarProps = {
  variant: "inset" | "floating" | "sidebar" | undefined;
};

export default function AppSidebar({ variant }: AppSidebarProps) {
  const { pathname } = useLocation();
  const logout = useLogout();

  const { data: user } = useQuery(currentUserQueryOptions);

  const handleLogout = async () => {
    try {
      await logout.mutateAsync();
      toast.success("Logout Successful");
    } catch (error) {
      if (error instanceof Error) {
        toast.error(`Failed to logout: ${error.message}`);
      } else {
        toast.error("Failed to logout");
      }
    }
  };

  return (
    <Sidebar variant={variant}>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel className="text-md mb-2">Mainframe</SidebarGroupLabel>
          <ModeToggle />
          <SidebarGroupContent>
            <SidebarMenu>
              {items.map((item) => {
                // 1. Determine if the link is active
                const isActive =
                  // Handle the root path separately
                  item.url === "/"
                    ? pathname === item.url
                    : // For other paths, check if the pathname starts with the item's URL
                      pathname.startsWith(item.url);

                return item.canAccess(user) ? (
                  <SidebarMenuItem key={item.title}>
                    <SidebarMenuButton
                      asChild
                      // 2. Apply the class based on the 'isActive' boolean
                      className={isActive ? "bg-accent" : ""}
                    >
                      <Link to={item.url}>
                        <item.icon />
                        <span>{item.title}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ) : null;
              })}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
      <SidebarFooter>
        <SidebarMenu>
          <SidebarMenuItem>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <SidebarMenuButton className="justify-center relative">
                  <User2 className="absolute left-2" />
                  <span>{user ? user.fullName : "Guest"}</span>
                  <ChevronUp className="absolute right-2 h-4 w-4" />
                </SidebarMenuButton>
              </DropdownMenuTrigger>
              <DropdownMenuContent side="top" className="w-[var(--radix-popper-anchor-width)]">
                <DropdownMenuItem onClick={handleLogout}>
                  <span>Logout</span>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarFooter>
    </Sidebar>
  );
}
