// frontend/src/components/layout/mode_toggle.tsx
import { Monitor, Moon, Sun } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown_menu";
import { useTheme } from "@/components/providers/theme_provider_functions";
import { SidebarGroupAction } from "@/components/ui/sidebar";

export function ModeToggle() {
  const { theme, setTheme } = useTheme();

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <SidebarGroupAction title="Toggle Theme" className="p-2 w-8 rounded-full">
          {/* Sun Icon: Visible in light mode */}
          <Sun
            className={`h-4 w-4 transition-all ${
              theme === "light" ? "rotate-0 scale-100" : "-rotate-90 scale-0"
            }`}
          />
          {/* Moon Icon: Visible in dark mode */}
          <Moon
            className={`absolute h-4 w-4 transition-all ${
              theme === "dark" ? "rotate-0 scale-100" : "rotate-90 scale-0"
            }`}
          />
          {/* Monitor Icon: Visible in system mode */}
          <Monitor
            className={`absolute h-4 w-4 transition-all ${
              theme === "system" ? "rotate-0 scale-100" : "rotate-90 scale-0"
            }`}
          />
        </SidebarGroupAction>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem
          onClick={() => setTheme("light")}
          className={theme === "light" ? "bg-accent" : ""}
        >
          <Sun /> Light
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => setTheme("dark")}
          className={theme === "dark" ? "bg-accent" : ""}
        >
          <Moon /> Dark
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => setTheme("system")}
          className={theme === "system" ? "bg-accent" : ""}
        >
          <Monitor /> System
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// solid-frontend/src/components/ui/mode-toggle/index.tsx
import { Monitor, Moon, Sun } from "lucide-solid";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { SidebarGroupAction } from "@/components/ui/sidebar";
import { localStorageManager, useColorMode, type ConfigColorMode } from "@kobalte/core";
import { createSignal, Match, Switch } from "solid-js";

export function ModeToggle() {
  const { setColorMode } = useColorMode();
  const [theme, setTheme] = createSignal<ConfigColorMode>("system");

  const handleOpenChange = (open: boolean) => {
    if (open) {
      // Read from localStorage when dropdown opens
      const stored = localStorageManager.get();
      if (stored) {
        setTheme(stored);
      }
    }
  };

  const handleThemeChange = (value: ConfigColorMode) => {
    setTheme(value);
    setColorMode(value);
  };

  return (
    <DropdownMenu onOpenChange={handleOpenChange}>
      <DropdownMenuTrigger
        as={SidebarGroupAction}
        title="Toggle Theme"
        class="p-2 w-8 rounded-full"
      >
        <Switch>
          <Match when={theme() === "light"}>
            <Sun />
          </Match>
          <Match when={theme() === "dark"}>
            <Moon />
          </Match>
          <Match when={theme() === "system"}>
            <Monitor />
          </Match>
        </Switch>
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        <DropdownMenuItem
          onClick={() => handleThemeChange("light")}
          class={theme() === "light" ? "bg-accent" : ""}
        >
          <Sun /> Light
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => handleThemeChange("dark")}
          class={theme() === "dark" ? "bg-accent" : ""}
        >
          <Moon /> Dark
        </DropdownMenuItem>
        <DropdownMenuItem
          onClick={() => handleThemeChange("system")}
          class={theme() === "system" ? "bg-accent" : ""}
        >
          <Monitor /> System
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
